const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities
const path = require('path');
const currentDir = process.cwd();
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'js/main': path.resolve(currentDir, 'src/js', 'main.ts'),
			'js/editor': path.resolve(currentDir, 'src/js', 'editor.ts'),
			'css/main': path.resolve(currentDir, 'src/scss', 'main.scss'),
			'css/editor': path.resolve(currentDir, 'src/scss', 'editor.scss'),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin({
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			}),
		].filter(Boolean),
	},
};
